/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TubesKelompok6IF3809.View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author A_CITRA
 */
public class MenuKelolaBarang extends javax.swing.JFrame implements View {

    /**
     * Creates new form MenuKelolaBarang
     */
    public MenuKelolaBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_tambahbarang = new javax.swing.JButton();
        btn_lihatdaftarbarang = new javax.swing.JButton();
        btn_ubahdata = new javax.swing.JButton();
        btn_peminjamanbarang = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        btn_lihatdaftarpeminjaman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Menu Kelola Barang");

        btn_tambahbarang.setBackground(new java.awt.Color(255, 204, 204));
        btn_tambahbarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_tambahbarang.setText("Tambah Data Barang");

        btn_lihatdaftarbarang.setBackground(new java.awt.Color(255, 204, 204));
        btn_lihatdaftarbarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_lihatdaftarbarang.setText("Lihat Daftar Barang");

        btn_ubahdata.setBackground(new java.awt.Color(255, 204, 204));
        btn_ubahdata.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_ubahdata.setText("Ubah Data Barang");

        btn_peminjamanbarang.setBackground(new java.awt.Color(255, 204, 204));
        btn_peminjamanbarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_peminjamanbarang.setText("Pinjam Barang");

        btn_kembali.setBackground(new java.awt.Color(255, 204, 204));
        btn_kembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_kembali.setText("Kembali");

        btn_lihatdaftarpeminjaman.setBackground(new java.awt.Color(255, 204, 204));
        btn_lihatdaftarpeminjaman.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_lihatdaftarpeminjaman.setText("Lihat Daftar Peminjaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_kembali)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 135, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_lihatdaftarpeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_peminjamanbarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ubahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_lihatdaftarbarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_tambahbarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(119, 119, 119))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btn_tambahbarang)
                .addGap(18, 18, 18)
                .addComponent(btn_lihatdaftarbarang)
                .addGap(18, 18, 18)
                .addComponent(btn_ubahdata)
                .addGap(18, 18, 18)
                .addComponent(btn_peminjamanbarang)
                .addGap(18, 18, 18)
                .addComponent(btn_lihatdaftarpeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_kembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_lihatdaftarbarang;
    private javax.swing.JButton btn_lihatdaftarpeminjaman;
    private javax.swing.JButton btn_peminjamanbarang;
    private javax.swing.JButton btn_tambahbarang;
    private javax.swing.JButton btn_ubahdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showMessage(String m) {
        JOptionPane.showMessageDialog(this, m);
    }

    @Override
    public void setListener(ActionListener a) {
        btn_kembali.addActionListener(a);
        btn_lihatdaftarbarang.addActionListener(a);
        btn_lihatdaftarpeminjaman.addActionListener(a);
        btn_peminjamanbarang.addActionListener(a);
        btn_tambahbarang.addActionListener(a);
        btn_ubahdata.addActionListener(a);
    }

    public JButton getBtn_ubahdata() {
        return btn_ubahdata;
    }

    public void setBtn_ubahdata(JButton btn_caribarang) {
        this.btn_ubahdata = btn_caribarang;
    }

    public JButton getBtn_kembali() {
        return btn_kembali;
    }

    public void setBtn_kembali(JButton btn_kembali) {
        this.btn_kembali = btn_kembali;
    }

    public JButton getBtn_lihatdaftarbarang() {
        return btn_lihatdaftarbarang;
    }

    public void setBtn_lihatdaftarbarang(JButton btn_lihatdaftarbarang) {
        this.btn_lihatdaftarbarang = btn_lihatdaftarbarang;
    }

    public JButton getBtn_peminjamanbarang() {
        return btn_peminjamanbarang;
    }

    public void setBtn_peminjamanbarang(JButton btn_peminjamanbarang) {
        this.btn_peminjamanbarang = btn_peminjamanbarang;
    }

    public JButton getBtn_tambahbarang() {
        return btn_tambahbarang;
    }

    public void setBtn_tambahbarang(JButton btn_tambahbarang) {
        this.btn_tambahbarang = btn_tambahbarang;
    }

    public JButton getBtn_lihatdaftarpeminjaman() {
        return btn_lihatdaftarpeminjaman;
    }

    public void setBtn_lihatdaftarpeminjaman(JButton btn_lihatdaftarpeminjaman) {
        this.btn_lihatdaftarpeminjaman = btn_lihatdaftarpeminjaman;
    }
    
    
    
}
